ClassNotFoundException: com.aayushatharva.brotli4j.decoder.DecoderJNI$Wrapper in Google Storage, PubSub and BigQuery test #2692
Fixed by the upgrade to Quarkus 2.0.0.CR3

This reverts commit ff1bf3a191db256a7a3835715a615dd8e5467d5c.